name: DL_protecto
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - scikit-learn
  - pandas
  - numpy==1.19.5
  - pytest
  - web3
  - re
  - seaborn
  - hexbytes
  - matplotlib
  - datasets

